[build]
  command = "bun run build"
  publish = "dist/client"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions."server"]
  included_files = ["dist/server/**"]