/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChaptersRouteImport } from './routes/chapters'
import { Route as CodeOfConductRouteImport } from './routes/code-of-conduct'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ContributorsRouteImport } from './routes/contributors'
import { Route as DoradaoRouteImport } from './routes/doradao'
import { Route as Doradao1RouteImport } from './routes/doradao-1'
import { Route as FellowshipRouteImport } from './routes/fellowship'
import { Route as HackWithDoraRouteImport } from './routes/hack-with-dora'
import { Route as PastInitiativesRouteImport } from './routes/past-initiatives'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReferRouteImport } from './routes/refer'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VoicesRouteImport } from './routes/voices'
import { Route as PartnerIndexRouteImport } from './routes/partner.index'
import { Route as PartnerCorporateRouteImport } from './routes/partner.corporate'
import { Route as PartnerCsrRouteImport } from './routes/partner.csr'
import { Route as PartnerEcosystemRouteImport } from './routes/partner.ecosystem'
import { Route as PartnerVolunteerRouteImport } from './routes/partner.volunteer'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as ProgramsIndexRouteImport } from './routes/programs.index'
import { Route as ProgramsBuildspaceRouteImport } from './routes/programs.buildspace'
import { Route as ProgramsDorahacksRouteImport } from './routes/programs.dorahacks'
import { Route as ProgramsGwy25RouteImport } from './routes/programs.gwy-25'
import { Route as ProgramsGwy26RouteImport } from './routes/programs.gwy-26'
import { Route as ProgramsW3mRouteImport } from './routes/programs.w3m'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersRoute = ChaptersRouteImport.update({
  id: '/chapters',
  path: '/chapters',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeOfConductRoute = CodeOfConductRouteImport.update({
  id: '/code-of-conduct',
  path: '/code-of-conduct',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributorsRoute = ContributorsRouteImport.update({
  id: '/contributors',
  path: '/contributors',
  getParentRoute: () => rootRouteImport,
} as any)
const DoradaoRoute = DoradaoRouteImport.update({
  id: '/doradao',
  path: '/doradao',
  getParentRoute: () => rootRouteImport,
} as any)
const Doradao1Route = Doradao1RouteImport.update({
  id: '/doradao-1',
  path: '/doradao-1',
  getParentRoute: () => rootRouteImport,
} as any)
const FellowshipRoute = FellowshipRouteImport.update({
  id: '/fellowship',
  path: '/fellowship',
  getParentRoute: () => rootRouteImport,
} as any)
const HackWithDoraRoute = HackWithDoraRouteImport.update({
  id: '/hack-with-dora',
  path: '/hack-with-dora',
  getParentRoute: () => rootRouteImport,
} as any)
const PastInitiativesRoute = PastInitiativesRouteImport.update({
  id: '/past-initiatives',
  path: '/past-initiatives',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferRoute = ReferRouteImport.update({
  id: '/refer',
  path: '/refer',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VoicesRoute = VoicesRouteImport.update({
  id: '/voices',
  path: '/voices',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerIndexRoute = PartnerIndexRouteImport.update({
  id: '/partner/',
  path: '/partner/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerCorporateRoute = PartnerCorporateRouteImport.update({
  id: '/partner/corporate',
  path: '/partner/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerCsrRoute = PartnerCsrRouteImport.update({
  id: '/partner/csr',
  path: '/partner/csr',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerEcosystemRoute = PartnerEcosystemRouteImport.update({
  id: '/partner/ecosystem',
  path: '/partner/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerVolunteerRoute = PartnerVolunteerRouteImport.update({
  id: '/partner/volunteer',
  path: '/partner/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsBuildspaceRoute = ProgramsBuildspaceRouteImport.update({
  id: '/programs/buildspace',
  path: '/programs/buildspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsDorahacksRoute = ProgramsDorahacksRouteImport.update({
  id: '/programs/dorahacks',
  path: '/programs/dorahacks',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsGwy25Route = ProgramsGwy25RouteImport.update({
  id: '/programs/gwy-25',
  path: '/programs/gwy-25',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsGwy26Route = ProgramsGwy26RouteImport.update({
  id: '/programs/gwy-26',
  path: '/programs/gwy-26',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsW3mRoute = ProgramsW3mRouteImport.update({
  id: '/programs/w3m',
  path: '/programs/w3m',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chapters': typeof ChaptersRoute
  '/code-of-conduct': typeof CodeOfConductRoute
  '/contact': typeof ContactRoute
  '/contributors': typeof ContributorsRoute
  '/doradao': typeof DoradaoRoute
  '/doradao-1': typeof Doradao1Route
  '/fellowship': typeof FellowshipRoute
  '/hack-with-dora': typeof HackWithDoraRoute
  '/past-initiatives': typeof PastInitiativesRoute
  '/privacy': typeof PrivacyRoute
  '/refer': typeof ReferRoute
  '/terms': typeof TermsRoute
  '/voices': typeof VoicesRoute
  '/partner/corporate': typeof PartnerCorporateRoute
  '/partner/csr': typeof PartnerCsrRoute
  '/partner/ecosystem': typeof PartnerEcosystemRoute
  '/partner/volunteer': typeof PartnerVolunteerRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/programs/buildspace': typeof ProgramsBuildspaceRoute
  '/programs/dorahacks': typeof ProgramsDorahacksRoute
  '/programs/gwy-25': typeof ProgramsGwy25Route
  '/programs/gwy-26': typeof ProgramsGwy26Route
  '/programs/w3m': typeof ProgramsW3mRoute
  '/partner/': typeof PartnerIndexRoute
  '/programs/': typeof ProgramsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chapters': typeof ChaptersRoute
  '/code-of-conduct': typeof CodeOfConductRoute
  '/contact': typeof ContactRoute
  '/contributors': typeof ContributorsRoute
  '/doradao': typeof DoradaoRoute
  '/doradao-1': typeof Doradao1Route
  '/fellowship': typeof FellowshipRoute
  '/hack-with-dora': typeof HackWithDoraRoute
  '/past-initiatives': typeof PastInitiativesRoute
  '/privacy': typeof PrivacyRoute
  '/refer': typeof ReferRoute
  '/terms': typeof TermsRoute
  '/voices': typeof VoicesRoute
  '/partner/corporate': typeof PartnerCorporateRoute
  '/partner/csr': typeof PartnerCsrRoute
  '/partner/ecosystem': typeof PartnerEcosystemRoute
  '/partner/volunteer': typeof PartnerVolunteerRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/programs/buildspace': typeof ProgramsBuildspaceRoute
  '/programs/dorahacks': typeof ProgramsDorahacksRoute
  '/programs/gwy-25': typeof ProgramsGwy25Route
  '/programs/gwy-26': typeof ProgramsGwy26Route
  '/programs/w3m': typeof ProgramsW3mRoute
  '/partner': typeof PartnerIndexRoute
  '/programs': typeof ProgramsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chapters': typeof ChaptersRoute
  '/code-of-conduct': typeof CodeOfConductRoute
  '/contact': typeof ContactRoute
  '/contributors': typeof ContributorsRoute
  '/doradao': typeof DoradaoRoute
  '/doradao-1': typeof Doradao1Route
  '/fellowship': typeof FellowshipRoute
  '/hack-with-dora': typeof HackWithDoraRoute
  '/past-initiatives': typeof PastInitiativesRoute
  '/privacy': typeof PrivacyRoute
  '/refer': typeof ReferRoute
  '/terms': typeof TermsRoute
  '/voices': typeof VoicesRoute
  '/partner/corporate': typeof PartnerCorporateRoute
  '/partner/csr': typeof PartnerCsrRoute
  '/partner/ecosystem': typeof PartnerEcosystemRoute
  '/partner/volunteer': typeof PartnerVolunteerRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/programs/buildspace': typeof ProgramsBuildspaceRoute
  '/programs/dorahacks': typeof ProgramsDorahacksRoute
  '/programs/gwy-25': typeof ProgramsGwy25Route
  '/programs/gwy-26': typeof ProgramsGwy26Route
  '/programs/w3m': typeof ProgramsW3mRoute
  '/partner/': typeof PartnerIndexRoute
  '/programs/': typeof ProgramsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chapters'
    | '/code-of-conduct'
    | '/contact'
    | '/contributors'
    | '/doradao'
    | '/doradao-1'
    | '/fellowship'
    | '/hack-with-dora'
    | '/past-initiatives'
    | '/privacy'
    | '/refer'
    | '/terms'
    | '/voices'
    | '/partner/corporate'
    | '/partner/csr'
    | '/partner/ecosystem'
    | '/partner/volunteer'
    | '/products/$slug'
    | '/programs/buildspace'
    | '/programs/dorahacks'
    | '/programs/gwy-25'
    | '/programs/gwy-26'
    | '/programs/w3m'
    | '/partner/'
    | '/programs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chapters'
    | '/code-of-conduct'
    | '/contact'
    | '/contributors'
    | '/doradao'
    | '/doradao-1'
    | '/fellowship'
    | '/hack-with-dora'
    | '/past-initiatives'
    | '/privacy'
    | '/refer'
    | '/terms'
    | '/voices'
    | '/partner/corporate'
    | '/partner/csr'
    | '/partner/ecosystem'
    | '/partner/volunteer'
    | '/products/$slug'
    | '/programs/buildspace'
    | '/programs/dorahacks'
    | '/programs/gwy-25'
    | '/programs/gwy-26'
    | '/programs/w3m'
    | '/partner'
    | '/programs'
  id:
    | '__root__'
    | '/'
    | '/chapters'
    | '/code-of-conduct'
    | '/contact'
    | '/contributors'
    | '/doradao'
    | '/doradao-1'
    | '/fellowship'
    | '/hack-with-dora'
    | '/past-initiatives'
    | '/privacy'
    | '/refer'
    | '/terms'
    | '/voices'
    | '/partner/corporate'
    | '/partner/csr'
    | '/partner/ecosystem'
    | '/partner/volunteer'
    | '/products/$slug'
    | '/programs/buildspace'
    | '/programs/dorahacks'
    | '/programs/gwy-25'
    | '/programs/gwy-26'
    | '/programs/w3m'
    | '/partner/'
    | '/programs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChaptersRoute: typeof ChaptersRoute
  CodeOfConductRoute: typeof CodeOfConductRoute
  ContactRoute: typeof ContactRoute
  ContributorsRoute: typeof ContributorsRoute
  DoradaoRoute: typeof DoradaoRoute
  Doradao1Route: typeof Doradao1Route
  FellowshipRoute: typeof FellowshipRoute
  HackWithDoraRoute: typeof HackWithDoraRoute
  PastInitiativesRoute: typeof PastInitiativesRoute
  PrivacyRoute: typeof PrivacyRoute
  ReferRoute: typeof ReferRoute
  TermsRoute: typeof TermsRoute
  VoicesRoute: typeof VoicesRoute
  PartnerCorporateRoute: typeof PartnerCorporateRoute
  PartnerCsrRoute: typeof PartnerCsrRoute
  PartnerEcosystemRoute: typeof PartnerEcosystemRoute
  PartnerVolunteerRoute: typeof PartnerVolunteerRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProgramsBuildspaceRoute: typeof ProgramsBuildspaceRoute
  ProgramsDorahacksRoute: typeof ProgramsDorahacksRoute
  ProgramsGwy25Route: typeof ProgramsGwy25Route
  ProgramsGwy26Route: typeof ProgramsGwy26Route
  ProgramsW3mRoute: typeof ProgramsW3mRoute
  PartnerIndexRoute: typeof PartnerIndexRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters': {
      id: '/chapters'
      path: '/chapters'
      fullPath: '/chapters'
      preLoaderRoute: typeof ChaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code-of-conduct': {
      id: '/code-of-conduct'
      path: '/code-of-conduct'
      fullPath: '/code-of-conduct'
      preLoaderRoute: typeof CodeOfConductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contributors': {
      id: '/contributors'
      path: '/contributors'
      fullPath: '/contributors'
      preLoaderRoute: typeof ContributorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doradao': {
      id: '/doradao'
      path: '/doradao'
      fullPath: '/doradao'
      preLoaderRoute: typeof DoradaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doradao-1': {
      id: '/doradao-1'
      path: '/doradao-1'
      fullPath: '/doradao-1'
      preLoaderRoute: typeof Doradao1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fellowship': {
      id: '/fellowship'
      path: '/fellowship'
      fullPath: '/fellowship'
      preLoaderRoute: typeof FellowshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hack-with-dora': {
      id: '/hack-with-dora'
      path: '/hack-with-dora'
      fullPath: '/hack-with-dora'
      preLoaderRoute: typeof HackWithDoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/past-initiatives': {
      id: '/past-initiatives'
      path: '/past-initiatives'
      fullPath: '/past-initiatives'
      preLoaderRoute: typeof PastInitiativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refer': {
      id: '/refer'
      path: '/refer'
      fullPath: '/refer'
      preLoaderRoute: typeof ReferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voices': {
      id: '/voices'
      path: '/voices'
      fullPath: '/voices'
      preLoaderRoute: typeof VoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/': {
      id: '/partner/'
      path: '/partner'
      fullPath: '/partner/'
      preLoaderRoute: typeof PartnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/corporate': {
      id: '/partner/corporate'
      path: '/partner/corporate'
      fullPath: '/partner/corporate'
      preLoaderRoute: typeof PartnerCorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/csr': {
      id: '/partner/csr'
      path: '/partner/csr'
      fullPath: '/partner/csr'
      preLoaderRoute: typeof PartnerCsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/ecosystem': {
      id: '/partner/ecosystem'
      path: '/partner/ecosystem'
      fullPath: '/partner/ecosystem'
      preLoaderRoute: typeof PartnerEcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/volunteer': {
      id: '/partner/volunteer'
      path: '/partner/volunteer'
      fullPath: '/partner/volunteer'
      preLoaderRoute: typeof PartnerVolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/programs'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/buildspace': {
      id: '/programs/buildspace'
      path: '/programs/buildspace'
      fullPath: '/programs/buildspace'
      preLoaderRoute: typeof ProgramsBuildspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/dorahacks': {
      id: '/programs/dorahacks'
      path: '/programs/dorahacks'
      fullPath: '/programs/dorahacks'
      preLoaderRoute: typeof ProgramsDorahacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/gwy-25': {
      id: '/programs/gwy-25'
      path: '/programs/gwy-25'
      fullPath: '/programs/gwy-25'
      preLoaderRoute: typeof ProgramsGwy25RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/gwy-26': {
      id: '/programs/gwy-26'
      path: '/programs/gwy-26'
      fullPath: '/programs/gwy-26'
      preLoaderRoute: typeof ProgramsGwy26RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/w3m': {
      id: '/programs/w3m'
      path: '/programs/w3m'
      fullPath: '/programs/w3m'
      preLoaderRoute: typeof ProgramsW3mRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChaptersRoute: ChaptersRoute,
  CodeOfConductRoute: CodeOfConductRoute,
  ContactRoute: ContactRoute,
  ContributorsRoute: ContributorsRoute,
  DoradaoRoute: DoradaoRoute,
  Doradao1Route: Doradao1Route,
  FellowshipRoute: FellowshipRoute,
  HackWithDoraRoute: HackWithDoraRoute,
  PastInitiativesRoute: PastInitiativesRoute,
  PrivacyRoute: PrivacyRoute,
  ReferRoute: ReferRoute,
  TermsRoute: TermsRoute,
  VoicesRoute: VoicesRoute,
  PartnerCorporateRoute: PartnerCorporateRoute,
  PartnerCsrRoute: PartnerCsrRoute,
  PartnerEcosystemRoute: PartnerEcosystemRoute,
  PartnerVolunteerRoute: PartnerVolunteerRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ProgramsBuildspaceRoute: ProgramsBuildspaceRoute,
  ProgramsDorahacksRoute: ProgramsDorahacksRoute,
  ProgramsGwy25Route: ProgramsGwy25Route,
  ProgramsGwy26Route: ProgramsGwy26Route,
  ProgramsW3mRoute: ProgramsW3mRoute,
  PartnerIndexRoute: PartnerIndexRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
